// <auto-generated />
using KannotEven.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KannotEven.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221206024111_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KannotEven.Models.Ingredient", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Ingredient");

                    b.HasData(
                        new
                        {
                            Name = "I0"
                        },
                        new
                        {
                            Name = "I1"
                        },
                        new
                        {
                            Name = "I2"
                        },
                        new
                        {
                            Name = "I3"
                        },
                        new
                        {
                            Name = "I4"
                        },
                        new
                        {
                            Name = "I5"
                        },
                        new
                        {
                            Name = "I6"
                        },
                        new
                        {
                            Name = "I7"
                        },
                        new
                        {
                            Name = "I8"
                        },
                        new
                        {
                            Name = "I9"
                        },
                        new
                        {
                            Name = "I10"
                        },
                        new
                        {
                            Name = "I11"
                        },
                        new
                        {
                            Name = "I12"
                        },
                        new
                        {
                            Name = "I13"
                        },
                        new
                        {
                            Name = "I14"
                        },
                        new
                        {
                            Name = "I15"
                        },
                        new
                        {
                            Name = "I16"
                        },
                        new
                        {
                            Name = "I17"
                        },
                        new
                        {
                            Name = "I18"
                        },
                        new
                        {
                            Name = "I19"
                        },
                        new
                        {
                            Name = "I20"
                        },
                        new
                        {
                            Name = "I21"
                        },
                        new
                        {
                            Name = "I22"
                        },
                        new
                        {
                            Name = "I23"
                        },
                        new
                        {
                            Name = "I24"
                        },
                        new
                        {
                            Name = "I25"
                        },
                        new
                        {
                            Name = "I26"
                        },
                        new
                        {
                            Name = "I27"
                        },
                        new
                        {
                            Name = "I28"
                        },
                        new
                        {
                            Name = "I29"
                        },
                        new
                        {
                            Name = "I30"
                        },
                        new
                        {
                            Name = "I31"
                        },
                        new
                        {
                            Name = "I32"
                        },
                        new
                        {
                            Name = "I33"
                        },
                        new
                        {
                            Name = "I34"
                        },
                        new
                        {
                            Name = "I35"
                        },
                        new
                        {
                            Name = "I36"
                        },
                        new
                        {
                            Name = "I37"
                        },
                        new
                        {
                            Name = "I38"
                        },
                        new
                        {
                            Name = "I39"
                        },
                        new
                        {
                            Name = "I40"
                        },
                        new
                        {
                            Name = "I41"
                        },
                        new
                        {
                            Name = "I42"
                        },
                        new
                        {
                            Name = "I43"
                        },
                        new
                        {
                            Name = "I44"
                        },
                        new
                        {
                            Name = "I45"
                        },
                        new
                        {
                            Name = "I46"
                        },
                        new
                        {
                            Name = "I47"
                        },
                        new
                        {
                            Name = "I48"
                        },
                        new
                        {
                            Name = "I49"
                        },
                        new
                        {
                            Name = "I50"
                        },
                        new
                        {
                            Name = "I51"
                        },
                        new
                        {
                            Name = "I52"
                        },
                        new
                        {
                            Name = "I53"
                        },
                        new
                        {
                            Name = "I54"
                        },
                        new
                        {
                            Name = "I55"
                        },
                        new
                        {
                            Name = "I56"
                        },
                        new
                        {
                            Name = "I57"
                        },
                        new
                        {
                            Name = "I58"
                        },
                        new
                        {
                            Name = "I59"
                        });
                });

            modelBuilder.Entity("KannotEven.Models.Recipe", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Recipe");

                    b.HasData(
                        new
                        {
                            Name = "R0",
                            URL = "www.test0.com"
                        },
                        new
                        {
                            Name = "R1",
                            URL = "www.test1.com"
                        },
                        new
                        {
                            Name = "R2",
                            URL = "www.test2.com"
                        },
                        new
                        {
                            Name = "R3",
                            URL = "www.test3.com"
                        },
                        new
                        {
                            Name = "R4",
                            URL = "www.test4.com"
                        },
                        new
                        {
                            Name = "R5",
                            URL = "www.test5.com"
                        },
                        new
                        {
                            Name = "R6",
                            URL = "www.test6.com"
                        },
                        new
                        {
                            Name = "R7",
                            URL = "www.test7.com"
                        },
                        new
                        {
                            Name = "R8",
                            URL = "www.test8.com"
                        },
                        new
                        {
                            Name = "R9",
                            URL = "www.test9.com"
                        },
                        new
                        {
                            Name = "R10",
                            URL = "www.test10.com"
                        },
                        new
                        {
                            Name = "R11",
                            URL = "www.test11.com"
                        },
                        new
                        {
                            Name = "R12",
                            URL = "www.test12.com"
                        },
                        new
                        {
                            Name = "R13",
                            URL = "www.test13.com"
                        },
                        new
                        {
                            Name = "R14",
                            URL = "www.test14.com"
                        },
                        new
                        {
                            Name = "R15",
                            URL = "www.test15.com"
                        },
                        new
                        {
                            Name = "R16",
                            URL = "www.test16.com"
                        },
                        new
                        {
                            Name = "R17",
                            URL = "www.test17.com"
                        },
                        new
                        {
                            Name = "R18",
                            URL = "www.test18.com"
                        },
                        new
                        {
                            Name = "R19",
                            URL = "www.test19.com"
                        });
                });

            modelBuilder.Entity("KannotEven.Models.Recipe_Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IngredientName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecipeName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientName");

                    b.HasIndex("RecipeName");

                    b.ToTable("Recipes_Ingredient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientName = "I0",
                            RecipeName = "R0"
                        },
                        new
                        {
                            Id = 2,
                            IngredientName = "I1",
                            RecipeName = "R1"
                        },
                        new
                        {
                            Id = 3,
                            IngredientName = "I2",
                            RecipeName = "R1"
                        },
                        new
                        {
                            Id = 4,
                            IngredientName = "I3",
                            RecipeName = "R1"
                        },
                        new
                        {
                            Id = 5,
                            IngredientName = "I4",
                            RecipeName = "R2"
                        },
                        new
                        {
                            Id = 6,
                            IngredientName = "I5",
                            RecipeName = "R2"
                        },
                        new
                        {
                            Id = 7,
                            IngredientName = "I6",
                            RecipeName = "R2"
                        },
                        new
                        {
                            Id = 8,
                            IngredientName = "I7",
                            RecipeName = "R3"
                        },
                        new
                        {
                            Id = 9,
                            IngredientName = "I8",
                            RecipeName = "R3"
                        },
                        new
                        {
                            Id = 10,
                            IngredientName = "I9",
                            RecipeName = "R3"
                        },
                        new
                        {
                            Id = 11,
                            IngredientName = "I10",
                            RecipeName = "R4"
                        },
                        new
                        {
                            Id = 12,
                            IngredientName = "I11",
                            RecipeName = "R4"
                        },
                        new
                        {
                            Id = 13,
                            IngredientName = "I12",
                            RecipeName = "R4"
                        },
                        new
                        {
                            Id = 14,
                            IngredientName = "I13",
                            RecipeName = "R5"
                        },
                        new
                        {
                            Id = 15,
                            IngredientName = "I14",
                            RecipeName = "R5"
                        },
                        new
                        {
                            Id = 16,
                            IngredientName = "I15",
                            RecipeName = "R5"
                        },
                        new
                        {
                            Id = 17,
                            IngredientName = "I16",
                            RecipeName = "R6"
                        },
                        new
                        {
                            Id = 18,
                            IngredientName = "I17",
                            RecipeName = "R6"
                        },
                        new
                        {
                            Id = 19,
                            IngredientName = "I18",
                            RecipeName = "R6"
                        },
                        new
                        {
                            Id = 20,
                            IngredientName = "I19",
                            RecipeName = "R7"
                        },
                        new
                        {
                            Id = 21,
                            IngredientName = "I20",
                            RecipeName = "R7"
                        },
                        new
                        {
                            Id = 22,
                            IngredientName = "I21",
                            RecipeName = "R7"
                        },
                        new
                        {
                            Id = 23,
                            IngredientName = "I22",
                            RecipeName = "R8"
                        },
                        new
                        {
                            Id = 24,
                            IngredientName = "I23",
                            RecipeName = "R8"
                        },
                        new
                        {
                            Id = 25,
                            IngredientName = "I24",
                            RecipeName = "R8"
                        },
                        new
                        {
                            Id = 26,
                            IngredientName = "I25",
                            RecipeName = "R9"
                        },
                        new
                        {
                            Id = 27,
                            IngredientName = "I26",
                            RecipeName = "R9"
                        },
                        new
                        {
                            Id = 28,
                            IngredientName = "I27",
                            RecipeName = "R9"
                        },
                        new
                        {
                            Id = 29,
                            IngredientName = "I28",
                            RecipeName = "R10"
                        },
                        new
                        {
                            Id = 30,
                            IngredientName = "I29",
                            RecipeName = "R10"
                        },
                        new
                        {
                            Id = 31,
                            IngredientName = "I30",
                            RecipeName = "R10"
                        },
                        new
                        {
                            Id = 32,
                            IngredientName = "I31",
                            RecipeName = "R11"
                        },
                        new
                        {
                            Id = 33,
                            IngredientName = "I32",
                            RecipeName = "R11"
                        },
                        new
                        {
                            Id = 34,
                            IngredientName = "I33",
                            RecipeName = "R11"
                        },
                        new
                        {
                            Id = 35,
                            IngredientName = "I34",
                            RecipeName = "R12"
                        },
                        new
                        {
                            Id = 36,
                            IngredientName = "I35",
                            RecipeName = "R12"
                        },
                        new
                        {
                            Id = 37,
                            IngredientName = "I36",
                            RecipeName = "R12"
                        },
                        new
                        {
                            Id = 38,
                            IngredientName = "I37",
                            RecipeName = "R13"
                        },
                        new
                        {
                            Id = 39,
                            IngredientName = "I38",
                            RecipeName = "R13"
                        },
                        new
                        {
                            Id = 40,
                            IngredientName = "I39",
                            RecipeName = "R13"
                        },
                        new
                        {
                            Id = 41,
                            IngredientName = "I40",
                            RecipeName = "R14"
                        },
                        new
                        {
                            Id = 42,
                            IngredientName = "I41",
                            RecipeName = "R14"
                        },
                        new
                        {
                            Id = 43,
                            IngredientName = "I42",
                            RecipeName = "R14"
                        },
                        new
                        {
                            Id = 44,
                            IngredientName = "I43",
                            RecipeName = "R15"
                        },
                        new
                        {
                            Id = 45,
                            IngredientName = "I44",
                            RecipeName = "R15"
                        },
                        new
                        {
                            Id = 46,
                            IngredientName = "I45",
                            RecipeName = "R15"
                        },
                        new
                        {
                            Id = 47,
                            IngredientName = "I46",
                            RecipeName = "R16"
                        },
                        new
                        {
                            Id = 48,
                            IngredientName = "I47",
                            RecipeName = "R16"
                        },
                        new
                        {
                            Id = 49,
                            IngredientName = "I48",
                            RecipeName = "R16"
                        },
                        new
                        {
                            Id = 50,
                            IngredientName = "I49",
                            RecipeName = "R17"
                        },
                        new
                        {
                            Id = 51,
                            IngredientName = "I50",
                            RecipeName = "R17"
                        },
                        new
                        {
                            Id = 52,
                            IngredientName = "I51",
                            RecipeName = "R17"
                        },
                        new
                        {
                            Id = 53,
                            IngredientName = "I52",
                            RecipeName = "R18"
                        },
                        new
                        {
                            Id = 54,
                            IngredientName = "I53",
                            RecipeName = "R18"
                        },
                        new
                        {
                            Id = 55,
                            IngredientName = "I54",
                            RecipeName = "R18"
                        },
                        new
                        {
                            Id = 56,
                            IngredientName = "I55",
                            RecipeName = "R19"
                        },
                        new
                        {
                            Id = 57,
                            IngredientName = "I56",
                            RecipeName = "R19"
                        },
                        new
                        {
                            Id = 58,
                            IngredientName = "I57",
                            RecipeName = "R19"
                        },
                        new
                        {
                            Id = 59,
                            IngredientName = "I58",
                            RecipeName = "R20"
                        },
                        new
                        {
                            Id = 60,
                            IngredientName = "I59",
                            RecipeName = "R20"
                        });
                });

            modelBuilder.Entity("KannotEven.Models.Recipe_Ingredient", b =>
                {
                    b.HasOne("KannotEven.Models.Ingredient", "Ingredient")
                        .WithMany("Recipe_Ingredients")
                        .HasForeignKey("IngredientName");

                    b.HasOne("KannotEven.Models.Recipe", "Recipe")
                        .WithMany("Recipe_Ingredients")
                        .HasForeignKey("RecipeName");
                });
#pragma warning restore 612, 618
        }
    }
}
